pipeline {
  agent any

  environment {
    IMAGE = "Techvengers7788/swiggy:${BUILD_NUMBER}"
  }

  stages {

    stage('Clean Workspace') {
      steps {
        cleanWs()
      }
    }

    stage('SonarQube Analysis') {
      environment {
        SCANNER_HOME = tool 'sonar-scanner'
      }
      steps {
        withSonarQubeEnv('sonar-server') {
          sh """
            ${SCANNER_HOME}/bin/sonar-scanner \
            -Dsonar.projectKey=swiggy \
            -Dsonar.sources=.
          """
        }
      }
    }

    stage('Dependency Scan') {
      steps {
        sh './security/dependency-check.sh'
      }
    }

   stage("Docker Build & Push"){
            steps{
                script{
                   withDockerRegistry(credentialsId: 'docker', toolName: 'docker'){   
                       sh "docker build --build-t swiggy ."
                       sh "docker tag netflix Techvengers7788/swiggy:latest "
                       sh "docker push Techvengers7788/swiggy:latest "
                    }
                }
            }
        }

stage("TRIVY"){
            steps{
                sh "trivy image Techvengers7788/swiggy:latest > trivyimage.txt" 
            }
        }

   stage('Deploy to container'){
            steps{
                sh 'docker run -d --name swiggy -p 8081:80 Techvengers7788/swiggy:latest'
            }
        }
        
    }
  
