pipeline {
  agent any

  environment {
    IMAGE = "techvengers7788/swiggy:${BUILD_NUMBER}"
    AWS_REGION = "ap-south-1"
    EKS_CLUSTER = "swiggy-eks-cluster"
  }

  stages {

    stage('Clean Workspace') {
      steps { cleanWs() }
    }

    stage('Git Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/Tech-Vengers/swiggy-clone'
      }
    }

    stage('SonarQube Analysis') {
      environment { SCANNER_HOME = tool 'sonar-scanner' }
      steps {
        withSonarQubeEnv('sonar-server') {
          sh """
            ${SCANNER_HOME}/bin/sonar-scanner \
            -Dsonar.projectKey=swiggy \
            -Dsonar.sources=.
          """
        }
      }
    }
/*
    stage('Dependency Scan') {
      steps {
        withCredentials([string(credentialsId: 'NVD_API_KEY', variable: 'NVD_API_KEY')]) {
          sh '''
          /opt/dependency-check/bin/dependency-check.sh \
            --scan Swiggy_clone \
            --format HTML \
            --out dependency-check-report \
            --data /opt/dependency-check-data \
            --nvdApiKey $NVD_API_KEY \
            --disableOssIndex \
            --disableNodeAudit \
            --disableRetireJS \
            --failOnCVSS 11
          '''
        }
      }
    }
*/
    stage('Docker Build & Push') {
      steps {
        script {
          withDockerRegistry(credentialsId: 'docker', toolName: 'docker') {
            sh """
              docker build -t $IMAGE ./Swiggy_clone
              docker push $IMAGE
              docker tag $IMAGE techvengers7788/swiggy:latest
              docker push techvengers7788/swiggy:latest
            """
          }
        }
      }
    }

    stage('Trivy Scan') {
      steps {
        sh 'trivy image $IMAGE > trivyimage.txt'
      }
    }

    stage('Deploy to EKS') {
      steps {
        withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']]) {
          sh '''
            aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER

            # Update image in deployment
            kubectl set image deployment/swiggy-deployment \
              swiggy=$IMAGE

            # Apply configs if first time
            kubectl apply -f k8s/deployment.yaml
            kubectl apply -f k8s/service.yaml

            kubectl rollout status deployment/swiggy-deployment
          '''
        }
      }
    }
  }
}
