pipeline {
  agent any

  environment {
    IMAGE = "Techvengers7788/swiggy:${BUILD_NUMBER}"
  }

  stages {

    stage('Clean Workspace') {
      steps {
        cleanWs()
      }
    }

    stage('SonarQube Analysis') {
      environment {
        SCANNER_HOME = tool 'sonar-scanner'
      }
      steps {
        withSonarQubeEnv('sonar-server') {
          sh """
            ${SCANNER_HOME}/bin/sonar-scanner \
            -Dsonar.projectKey=swiggy \
            -Dsonar.sources=.
          """
        }
      }
    }

    stage('Dependency Scan') {
      steps {
        sh './security/dependency-check.sh'
      }
    }

    stage('Docker Build & Push') {
      steps {
        script {
          withDockerRegistry(credentialsId: 'docker', toolName: 'docker') {
            sh """
              docker build -t $IMAGE .
              docker push $IMAGE
            """
          }
        }
      }
    }

    stage('Trivy Scan') {
      steps {
        sh 'trivy image $IMAGE > trivyimage.txt'
      }
    }

    stage('Deploy Container') {
      steps {
        sh '''
          docker rm -f swiggy || true
          docker run -d --name swiggy -p 8081:80 $IMAGE
        '''
      }
    }
  }
}
